[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day01a"
path = "2021/day01a/main.rs"

[[bin]]
name = "day01b"
path = "2021/day01b/main.rs"

[[bin]]
name = "day02a"
path = "2021/day02a/main.rs"

[[bin]]
name = "day02b"
path = "2021/day02b/main.rs"

[[bin]]
name = "day03a"
path = "2021/day03a/main.rs"

[[bin]]
name = "day03b"
path = "2021/day03b/main.rs"